#!/bin/bash

userName=$USER
today=$(date +%y-%m-%d/%l:%M:%S)
comp_hostname=$(hostname)
userUptime=$(uptime)
cpuInfo=$(lscpu | grep -i 'Model name:' | cut -d':' -f2 | tr -d '[:space:]')
cpuSpeed=$(cat /proc/cpuinfo | grep -i 'cpu mhz' | head -n 1 | awk '{print $4}')
ramSize=$(free -h | grep -i "mem:" | awk '{print $2}')
osSource=$(cat /etc/os-release | grep "PRETTY_NAME" | cut -d= -f2)
disks1=$(lsblk -dno model | tr -d '[:space:]' | cut -dS -f1)
diskSize1=$(lsblk -dno size | tail -n 3 | awk '{print $1}' | sed -n '1p')
disks2=$(lsblk -dno model | tr -d '[:space:]' | cut -dS -f2)
diskSize2=$(lsblk -dno size | tail -n 2 | awk '{print $1}'| sed -n '1p')
vidCardMake=$(lshw -class display | grep -i 'vendor:' | cut -d':' -f2)
vidCard=$(lshw -class display | grep -i 'product:' | cut -d':' -f2)
ipAddress=$(ip addr show | awk '/inet /{print $2}' | sed -n '2p')
fqdn=$(nmcli | awk '/domains: / {print $2}' | sed -n '2p')
hostAddress=$(ip addr show | awk '/inet /{print $2}' | cut -d'/' -f1 | sed -n '2p')
gatewayIP=$(ip route | awk '/default /{print $3}')
networkMake=$(lshw -class network | awk '/vendor: /' | head -n 1 | cut -d':' -f2)
networkCard=$(lshw -class network | awk '/product: /'| head -n 1 | cut -d':' -f2)
dnsServer=$(nmcli | awk '/servers: /{print $2}'| sed -n '1p')
usersLoggedIn=$(getent passwd | tail -n 2 | cut -d':' -f1 | sed -n '1p'); $(getent passwd | tail -n 2 | cut -d':' -f1 | sed -n '2p')

cat <<EOF

System Report generated by $userName, $today
 
 
System Information
------------------
HOSTNAME: $comp_hostname
OS: $osSource
Uptime: $userUptime

Hardware Information 
--------------------
CPU: $cpuInfo
Speed: $cpuSpeed
RAM: $ramSize
Disks: $disks1 - $diskSize1, $disks2 - $diskSize2
Videocard: $vidCardMake$vidCard

Network Information
-------------------
FQDN: $comp_hostname.$fqdn
Host Address: $hostAddress
Gateway IP: $gatewayIP
DNS Server: $dnsServer
Interface Name: $networkMake$networkCard
IP Address: $ipAddress

System Status
-------------
Users Logged In: $usersLoggedIn
Disk Space: 
Process Count: 
Load Averages: 
Memory Allocation: 
Listening Network Ports: 
UFW Rules: 

EOF
